apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: uct6aspvv-go-gitops
  description: This is GitOps manifest for uct6aspvv-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: uct6aspvv-go
    backstage.io/kubernetes-id: uct6aspvv-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: uct6aspvv-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:uct6aspvv-go
